version: "2"

services:
  web:
    build: ./app
    ports:
      - "3000"
    command: nodemon -L app/bin/www
    networks:
      default:
        aliases:
          - "web"
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/public
      - /etc/letsencrypt:/certs
    volumes_from:
      - web

  db:
    image: mysql
    volumes:
      - ./dbinit:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306"
    networks:
      default:
        aliases:
          - "my-db"
